name: r-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - r-base
  - r-essentials
  - bioconductor-biomart
  - r-tidyverse
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
